### ISSUE TITLE
Add a rake task redis:vacuum  

### ISSUE THREAD

**Issue by donaldong** [chanzuckerberg/redcord#12]
This rake tasks can be used to remove deleted indices due to TTL. This task should be run periodically to avoid bloating the Redis DB.

**Comment by katyho** [comment]
I was thinking of how to implement the vacuum task for Redcord. Just want to confirm the implementation and I'm not missing anything obvious (it's also been awhile since I've worked on redcord 😧 )
- The goal is to remove ids from index sets which have already expired due to ttl.
- We can query for Model.where('updated_at < Time.now - TTL') to get the id’s of all the records which have already expired due to ttl.
- We don’t have what the record values and attributes were before it expired, so we can’t directly know which index set to remove from. Would we have to scan through all of them then?

cc @donaldong

**Comment by donaldong** [comment]
> * We can query for Model.where('updated_at < Time.now - TTL') to get the id’s of all the records which have already expired due to ttl.

iirc the actual model would have been deleted so the where query won't return anything?


> * We don’t have what the record values and attributes were before it expired, so we can’t directly know which index set to remove from. Would we have to scan through all of them then?

Yeah that's what I have in mind as well. The operations should not be in a transaction/pipeline since it can take a while to run and we don't want it to block other operations.

Some thoughts:
- fast vacuum: can we randomly sample some indexed sets to vacuum?
- full vacuum: really loop through all index sets -- What if the task is aborted at 50%? should we start at 0% again? or should we implement a "checkpoint"?

**Comment by katyho** [comment]
> iirc the actual model would have been deleted so the where query won't return anything?

Ah yeah you're right this won't return anything. That makes sense to me!

**Comment by katyho** [comment]
Some other thoughts about the implementation. Here's a basic implementation of a full vacuum: https://github.com/chanzuckerberg/redcord/pull/65

For a vacuum sample implementation, we can sample random index sets by doing a limited number of scans while matching for `Redcord:Model:attr:*`. 

We can sample ids in the index sets (as opposed to scanning all ids in the whole set) by using [srandmember](https://redis.io/commands/srandmember) for regular sets; for sorted sets, there's no native Redis command to do this but we can do something like generating a random rank based on the cardinality of the set: https://redis.io/commands/zrank

=====

Another potential direction for this is to enable keyspace notifications on Redis and always have a background operation that listens to expire events: https://redis.io/topics/notifications so we know when and what ids to expire instead of scanning through the sets. It utilizes additional CPU though, so I think it'd require some more experimentation.

> By default keyspace event notifications are disabled because while not very sensible the feature uses some CPU power. Notifications are enabled using the notify-keyspace-events of redis.conf or via the CONFIG SET.
